'use client';
import { useState } from 'react';
import { ArrowRight, Check, ChevronRight, Cloud, Cpu, Database, LayoutDashboard, Menu, Server, ShieldCheck, ShoppingCart, Sparkles, Wallet, X, Zap } from 'lucide-react';

const plans=[['1 GB','1 vCPU','5 GB','Rp 5.000'],['2 GB','1 vCPU','10 GB','Rp 8.000'],['4 GB','2 vCPU','20 GB','Rp 14.000'],['6 GB','3 vCPU','30 GB','Rp 20.000'],['8 GB','4 vCPU','40 GB','Rp 28.000'],['10 GB','5 vCPU','50 GB','Rp 35.000'],['Unlimited','Unlimited','Unlimited','Rp 75.000']];

export default function Home(){
 const [mobile,setMobile]=useState(false); const [modal,setModal]=useState(false); const [selected,setSelected]=useState('4 GB');
 const order=()=>setModal(true);
 return <main>
  <header className="top"><div className="nav wrap"><div className="brand"><span className="brandMark"><Zap size={18}/></span><span>FELIX <b>PANEL</b></span></div><nav className={mobile?'open':''}>{['Home','Panel','Reseller','Admin Panel','Harga','Cara Order','Leaderboard','Bantuan'].map(x=><a key={x} href={'#'+x.toLowerCase().replaceAll(' ','-')} onClick={()=>setMobile(false)}>{x}</a>)}<button className="ghost">Login</button><button className="primary small">Daftar</button></nav><button className="iconBtn mobileMenu" onClick={()=>setMobile(!mobile)}>{mobile?<X/>:<Menu/>}</button></div></header>
  <section className="hero wrap"><div className="heroCopy"><div className="eyebrow"><Sparkles size={15}/> Auto provisioning marketplace</div><h1>Auto Order <span>Pterodactyl Panel</span></h1><p>Pesan panel Pterodactyl secara otomatis, cepat, aman, dan tanpa menunggu admin.</p><div className="actions"><button className="primary" onClick={order}>Mulai Order <ArrowRight size={18}/></button><a className="softBtn" href="#harga">Lihat Harga</a></div><div className="trust"><span><Check size={15}/> Pembayaran otomatis</span><span><Check size={15}/> Provisioning cepat</span><span><Check size={15}/> Support 24/7</span></div></div><div className="heroVisual"><div className="floatCard one"><Cloud size={18}/><div><b>Server Online</b><small>99.9% uptime</small></div></div><div className="dashCard"><div className="dashTop"><span>Dashboard</span><span className="live">● Live</span></div><div className="dashStats"><div><small>Saldo</small><strong>Rp 250.000</strong></div><div><small>Total Order</small><strong>24</strong></div></div><div className="serverRow"><span className="serverIcon"><Server size={19}/></span><div><b>Felix Production</b><small>4 GB · 2 vCPU · Node.js</small></div><span className="onlineDot"/></div><div className="meter"><i/></div></div><div className="floatCard two"><ShieldCheck size={18}/><div><b>Secure</b><small>API protected</small></div></div></div></section>
  <section className="stats wrap"><Stat icon={<Server/>} n="10+" t="Pilihan Paket"/><Stat icon={<Zap/>} n="< 1 Menit" t="Provisioning"/><Stat icon={<ShieldCheck/>} n="100%" t="Server-side"/><Stat icon={<Wallet/>} n="Otomatis" t="Pembayaran"/></section>
  <section id="harga" className="section wrap"><div className="sectionHead"><div><span className="label">PILIH PAKET</span><h2>Panel yang sesuai kebutuhan</h2><p>Harga dan konfigurasi nantinya dikelola penuh dari Admin Website.</p></div><a href="#panel" className="softBtn">Lihat semua <ChevronRight size={16}/></a></div><div className="plans">{plans.map(([ram,cpu,disk,price],i)=><article className={'plan '+(i===2?'featured':'')} key={ram}>{i===2&&<span className="popular">Paling populer</span>}<div className="planIcon"><Server size={20}/></div><h3>{ram}</h3><div className="price">{price}<small>/ order</small></div><div className="features"><span><Cpu size={15}/>{cpu}</span><span><Database size={15}/>{disk} disk</span><span><Check size={15}/>Node.js / Python</span></div><button className={i===2?'primary full':'softBtn full'} onClick={()=>{setSelected(ram);order()}}>Order {ram}</button></article>)}</div></section>
  <section id="reseller" className="section softSection"><div className="wrap split"><div><span className="label">RESELLER</span><h2>Bangun bisnis panelmu sendiri.</h2><p>Dapatkan harga reseller, kelola customer, pantau profit, dan buat panel untuk customer dari satu dashboard.</p><div className="checkList"><span><Check/> Harga reseller configurable</span><span><Check/> Profit & transaksi</span><span><Check/> Customer order</span><span><Check/> Voucher reseller</span></div><button className="primary" onClick={order}>Mulai Jadi Reseller <ArrowRight size={18}/></button></div><div className="resellerCard"><div className="miniHead"><span>Reseller Dashboard</span><span>Profit</span></div><strong>Rp 3.250.000</strong><div className="profitLine"><span>Sales bulan ini</span><b>128 order</b></div><div className="bars"><i/><i/><i/><i/><i/><i/><i/></div></div></div></section>
  <section className="section wrap"><div className="sectionHead center"><span className="label">CARA ORDER</span><h2>Order selesai dalam beberapa langkah</h2><p>Flow dibuat singkat supaya user bisa memahami proses dalam hitungan detik.</p></div><div className="steps">{['Pilih produk','Pilih RAM & Egg','Isi data panel','Bayar via QRIS','Server dibuat otomatis'].map((x,i)=><div className="step" key={x}><span>{String(i+1).padStart(2,'0')}</span><h3>{x}</h3><p>{i===4?'Login dan detail server langsung tersedia.':'Konfigurasi disimpan dan divalidasi server.'}</p></div>)}</div></section>
  <section className="cta wrap"><div><span className="label">FELIX PANEL</span><h2>Siap punya panel dalam hitungan menit?</h2><p>Mulai order sekarang. Pembayaran dan provisioning dirancang otomatis.</p></div><button className="primary" onClick={order}>Mulai Order <ArrowRight size={18}/></button></section>
  <footer><div className="wrap footerGrid"><div><div className="brand"><span className="brandMark"><Zap size={18}/></span><span>FELIX <b>PANEL</b></span></div><p>Auto Order Pterodactyl Panel.</p></div><div><b>Produk</b><a href="#harga">Harga</a><a href="#reseller">Reseller</a><a href="#">Admin Panel</a></div><div><b>Bantuan</b><a href="#">Cara Order</a><a href="#">FAQ</a><a href="#">Contact</a></div><div><b>Legal</b><a href="#">Terms</a><a href="#">Privacy</a></div></div><div className="copyright wrap">© 2026 FELIX PANEL. All rights reserved.</div></footer>
  <div className="bottomNav"><a href="#"><LayoutDashboard size={19}/><span>Home</span></a><a href="#harga"><ShoppingCart size={19}/><span>Order</span></a><button onClick={order}><Wallet size={19}/><span>Deposit</span></button><a href="#"><ShieldCheck size={19}/><span>Notifikasi</span></a><a href="#"><span className="avatar">F</span><span>Profile</span></a></div>
  {modal&&<div className="modalBackdrop" onClick={()=>setModal(false)}><div className="modal" onClick={e=>e.stopPropagation()}><button className="close" onClick={()=>setModal(false)}><X/></button><div className="modalIcon"><ShoppingCart/></div><h2>Login diperlukan</h2><p>Silakan login atau daftar akun untuk melanjutkan order <b>{selected}</b>.</p><div className="modalActions"><button className="softBtn full" onClick={()=>setModal(false)}>Login</button><button className="primary full" onClick={()=>setModal(false)}>Daftar Akun</button></div></div></div>}
 </main>
}
function Stat({icon,n,t}:{icon:React.ReactNode,n:string,t:string}){return <div className="stat"><span className="statIcon">{icon}</span><div><strong>{n}</strong><small>{t}</small></div></div>}
